[server]

[data]

[limits]

[[repositories]]
id = "main"
provider = "git"
uri = "."
display_name = "Yoi"
default_selector = "HEAD"

[[runtimes.remote]]
id = "arc"
endpoint = "http://127.0.0.1:38800"
display_name = "arc"
