[workspace]
resolver = "2"
members = [
    "crates/daemon",
    "crates/llm-worker",
    "crates/llm-worker-macros",
    "crates/session-store",
    "crates/manifest",
    "crates/pod",
    "crates/protocol",
    "crates/provider",
    "crates/pod-registry",
    "crates/tools",
    "crates/tui", "crates/memory",
]

[workspace.package]
edition = "2024"
license = "MIT"
