[workspace]
resolver = "2"
members = [
    "crates/daemon",
    "crates/llm-worker",
    "crates/llm-worker-macros",
    "crates/llm-worker-persistence",
    "crates/manifest",
    "crates/pod",
    "crates/protocol",
    "crates/provider",
    "crates/tui",
]

[workspace.package]
edition = "2024"
license = "MIT"
