use std::path::PathBuf;

use serde_json::{Map, Value};
use ts_rs::{Config, TS};

use crate::{
    Alert, AlertLevel, AlertSource, CommandEvent, CommandSnapshot, CommandStatus, CommandStream,
    CommandStreamSlice, CompactionLifecycle, CompactionLifecycleState, CompactionPhase,
    CompactionTrigger, CompletionEntry, CompletionKind, ErrorCode, Event, Greeting, InFlightBlock,
    InFlightCompaction, InFlightSnapshot, InFlightToolCallState, InternalWorkerKind,
    InternalWorkerRef, InternalWorkerSnapshot, InvokeKind, MemoryWorkerEvent, Method,
    PasteArtifactAvailability, PasteArtifactMediaType, PasteArtifactRef, PendingSubmissionSummary,
    PendingSubmissionsSnapshot, Permission, RewindSummary, RewindTarget, RewindTargetId, RunResult,
    ScopeRule, Segment, SessionContentPart, SessionEntryProvenance, SessionMessageRole,
    SessionSnapshot, SessionSnapshotEntry, SessionSnapshotEntryData, SessionToolAttachment,
    SubmissionDisposition, SymlinkPolicy, ToolResultDisposition, TurnResult,
    UploadedFileAvailability, UploadedFileRef, WorkerBusyState, WorkerCommandAcknowledgement,
    WorkerCommandDisposition, WorkerCommandEnvelope, WorkerCommandKind, WorkerEvent,
    WorkerMaintenanceState, WorkerRunState, WorkerState, WorkerStateSnapshot, WorkerStatus,
    subscription::{
        EventSubscriptionSelector, MAX_CORRELATION_ID_BYTES, MAX_REJECTION_MESSAGE_BYTES,
        MAX_RESOURCE_ID_BYTES, MAX_SUBSCRIPTION_COLLECTION_ITEMS,
        MAX_SUBSCRIPTION_FRAME_JSON_BYTES, MAX_SUBSCRIPTION_STRING_BYTES,
        MAX_SUBSCRIPTION_VALUE_DEPTH, MAX_SUBSCRIPTION_VALUE_NODES, MAX_WORKER_IDS_PER_SELECTOR,
        SUBSCRIPTION_PROTOCOL_VERSION, SubscriptionEvent, SubscriptionEventPayload,
        SubscriptionFrame, SubscriptionFramePayload, SubscriptionId, SubscriptionRejectionCode,
        SubscriptionRequest, SubscriptionRequestId, SubscriptionResponse, SubscriptionSnapshot,
        SubscriptionTerminationCode, SubscriptionWorkdirId, SubscriptionWorker,
        SubscriptionWorkerAvailability, SubscriptionWorkerId, SubscriptionWorkerIds,
        SubscriptionWorkerProtocolMethod, SubscriptionWorkerState,
        SubscriptionWorkerWorkdirAttachment, WorkspaceSubscriptionWorkdir,
    },
};

const GENERATED_RELATIVE_PATH: &str = "../../web/workspace/src/lib/generated/protocol.ts";
const GENERATED_VALIDATOR_RELATIVE_PATH: &str =
    "../../web/workspace/src/lib/generated/protocol-validator.ts";

/// Repository-relative destination for the Workspace web protocol bindings.
pub fn generated_typescript_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(GENERATED_RELATIVE_PATH)
}

/// Repository-relative destination for the generated Workspace Browser validator.
pub fn generated_runtime_validator_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(GENERATED_VALIDATOR_RELATIVE_PATH)
}

/// Render Workspace web TypeScript bindings for the Worker wire protocol DTOs.
///
/// Rust DTOs in this crate remain the source of truth; this function is used by
/// both the checked-in artifact generator and the stale-output drift test.
pub fn generated_protocol_types() -> String {
    let cfg = Config::new().with_large_int("number");
    let mut output = String::from(
        "// @generated by `cargo run -p protocol --example generate_typescript --features typescript`\n\
         // Do not edit by hand. Rust DTO authority lives in `crates/protocol`.\n\
         // Large integer fields are JSON numbers on the wire and are emitted as TypeScript `number`.\n\n",
    );

    push_decl::<AlertLevel>(&cfg, &mut output);
    push_decl::<AlertSource>(&cfg, &mut output);
    push_decl::<CompletionKind>(&cfg, &mut output);
    push_decl::<WorkerStatus>(&cfg, &mut output);
    push_decl::<WorkerCommandEnvelope>(&cfg, &mut output);
    push_decl::<WorkerCommandKind>(&cfg, &mut output);
    push_decl::<WorkerCommandDisposition>(&cfg, &mut output);
    push_decl::<WorkerCommandAcknowledgement>(&cfg, &mut output);
    push_decl::<WorkerRunState>(&cfg, &mut output);
    push_decl::<WorkerMaintenanceState>(&cfg, &mut output);
    push_decl::<WorkerBusyState>(&cfg, &mut output);
    push_decl::<WorkerState>(&cfg, &mut output);
    push_decl::<WorkerStateSnapshot>(&cfg, &mut output);
    push_decl::<TurnResult>(&cfg, &mut output);
    push_decl::<InvokeKind>(&cfg, &mut output);
    push_decl::<RunResult>(&cfg, &mut output);
    push_decl::<ToolResultDisposition>(&cfg, &mut output);
    push_decl::<ErrorCode>(&cfg, &mut output);
    push_decl::<Permission>(&cfg, &mut output);
    push_decl::<SymlinkPolicy>(&cfg, &mut output);
    push_decl::<InFlightToolCallState>(&cfg, &mut output);
    push_decl::<CommandStatus>(&cfg, &mut output);
    push_decl::<CommandStream>(&cfg, &mut output);
    push_decl::<CommandStreamSlice>(&cfg, &mut output);
    push_decl::<CommandSnapshot>(&cfg, &mut output);
    push_decl::<CommandEvent>(&cfg, &mut output);
    push_decl::<CompactionLifecycleState>(&cfg, &mut output);
    push_decl::<CompactionLifecycle>(&cfg, &mut output);
    push_decl::<CompactionPhase>(&cfg, &mut output);
    push_decl::<CompactionTrigger>(&cfg, &mut output);
    push_decl::<UploadedFileAvailability>(&cfg, &mut output);
    push_decl::<UploadedFileRef>(&cfg, &mut output);
    push_decl::<ScopeRule>(&cfg, &mut output);
    push_decl::<CompletionEntry>(&cfg, &mut output);
    push_decl::<RewindTargetId>(&cfg, &mut output);
    push_decl::<RewindTarget>(&cfg, &mut output);
    push_decl::<RewindSummary>(&cfg, &mut output);
    push_decl::<InFlightBlock>(&cfg, &mut output);
    push_decl::<InFlightCompaction>(&cfg, &mut output);
    push_decl::<InFlightSnapshot>(&cfg, &mut output);
    push_decl::<SessionEntryProvenance>(&cfg, &mut output);
    push_decl::<SessionMessageRole>(&cfg, &mut output);
    push_decl::<SessionContentPart>(&cfg, &mut output);
    push_decl::<SessionToolAttachment>(&cfg, &mut output);
    push_decl::<SessionSnapshotEntryData>(&cfg, &mut output);
    push_decl::<SessionSnapshotEntry>(&cfg, &mut output);
    push_decl::<PendingSubmissionSummary>(&cfg, &mut output);
    push_decl::<PendingSubmissionsSnapshot>(&cfg, &mut output);
    push_decl::<SubmissionDisposition>(&cfg, &mut output);
    push_decl::<SessionSnapshot>(&cfg, &mut output);
    push_decl::<InternalWorkerKind>(&cfg, &mut output);
    push_decl::<InternalWorkerRef>(&cfg, &mut output);
    push_decl::<InternalWorkerSnapshot>(&cfg, &mut output);
    push_decl::<Greeting>(&cfg, &mut output);
    push_decl::<Alert>(&cfg, &mut output);
    push_decl::<MemoryWorkerEvent>(&cfg, &mut output);
    push_decl::<PasteArtifactMediaType>(&cfg, &mut output);
    push_decl::<PasteArtifactAvailability>(&cfg, &mut output);
    push_decl::<PasteArtifactRef>(&cfg, &mut output);
    push_decl::<Segment>(&cfg, &mut output);
    push_decl::<WorkerEvent>(&cfg, &mut output);
    push_decl::<SubscriptionRequestId>(&cfg, &mut output);
    push_decl::<SubscriptionId>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerId>(&cfg, &mut output);
    push_decl::<SubscriptionWorkdirId>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerIds>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerState>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerAvailability>(&cfg, &mut output);
    push_decl::<EventSubscriptionSelector>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerWorkdirAttachment>(&cfg, &mut output);
    push_decl::<SubscriptionWorker>(&cfg, &mut output);
    push_decl::<WorkspaceSubscriptionWorkdir>(&cfg, &mut output);
    push_decl::<SubscriptionSnapshot>(&cfg, &mut output);
    push_decl::<SubscriptionEventPayload>(&cfg, &mut output);
    push_decl::<SubscriptionRejectionCode>(&cfg, &mut output);
    push_decl::<SubscriptionTerminationCode>(&cfg, &mut output);
    push_decl::<SubscriptionRequest>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerProtocolMethod>(&cfg, &mut output);
    push_decl::<SubscriptionResponse>(&cfg, &mut output);
    push_decl::<SubscriptionEvent>(&cfg, &mut output);
    push_decl::<SubscriptionFramePayload>(&cfg, &mut output);
    push_decl::<SubscriptionFrame>(&cfg, &mut output);
    push_decl::<Method>(&cfg, &mut output);
    push_decl::<Event>(&cfg, &mut output);

    normalize_typescript(output)
}

/// Render the strict runtime validator paired with the generated declarations.
///
/// `schemars` projects the reachable Serde shape from [`SubscriptionFrame`]. The
/// normalization closes every object and expands flattened enum payloads before
/// embedding that schema into the dependency-free Browser validator template.
pub fn generated_protocol_validator() -> String {
    let mut schema = serde_json::to_value(schemars::schema_for!(SubscriptionFrame))
        .expect("SubscriptionFrame schema must serialize");
    close_object_shapes(&mut schema);
    let schema = serde_json::to_string(&schema).expect("SubscriptionFrame schema must serialize");
    include_str!("typescript_validator_template.ts")
        .replace(
            "__GENERATED_PREAMBLE__",
            "// @generated by `cargo run -p protocol --example generate_typescript --features typescript`\n// Do not edit by hand. Rust DTO and validation authority lives in `crates/protocol`.",
        )
        .replace(
            "__PROTOCOL_VERSION__",
            &SUBSCRIPTION_PROTOCOL_VERSION.to_string(),
        )
        .replace(
            "__MAX_FRAME_BYTES__",
            &MAX_SUBSCRIPTION_FRAME_JSON_BYTES.to_string(),
        )
        .replace(
            "__MAX_STRING_BYTES__",
            &MAX_SUBSCRIPTION_STRING_BYTES.to_string(),
        )
        .replace(
            "__MAX_COLLECTION_ITEMS__",
            &MAX_SUBSCRIPTION_COLLECTION_ITEMS.to_string(),
        )
        .replace(
            "__MAX_VALUE_DEPTH__",
            &MAX_SUBSCRIPTION_VALUE_DEPTH.to_string(),
        )
        .replace(
            "__MAX_VALUE_NODES__",
            &MAX_SUBSCRIPTION_VALUE_NODES.to_string(),
        )
        .replace(
            "__MAX_CORRELATION_ID_BYTES__",
            &MAX_CORRELATION_ID_BYTES.to_string(),
        )
        .replace(
            "__MAX_RESOURCE_ID_BYTES__",
            &MAX_RESOURCE_ID_BYTES.to_string(),
        )
        .replace(
            "__MAX_WORKER_IDS_PER_SELECTOR__",
            &MAX_WORKER_IDS_PER_SELECTOR.to_string(),
        )
        .replace(
            "__MAX_REJECTION_MESSAGE_BYTES__",
            &MAX_REJECTION_MESSAGE_BYTES.to_string(),
        )
        .replace("__SUBSCRIPTION_FRAME_SCHEMA__", &schema)
}

fn close_object_shapes(schema: &mut Value) {
    let Value::Object(object) = schema else {
        if let Value::Array(values) = schema {
            for value in values {
                close_object_shapes(value);
            }
        }
        return;
    };

    expand_flattened_object(object);
    for value in object.values_mut() {
        close_object_shapes(value);
    }
    if object.get("type").and_then(Value::as_str) == Some("object")
        && object.contains_key("properties")
    {
        object.insert("additionalProperties".to_string(), Value::Bool(false));
    }
}

/// Serde flatten is represented by schemars as object properties beside `oneOf`.
/// Move those common properties into each object alternative so standard JSON
/// Schema `additionalProperties: false` has the intended exact-shape semantics.
fn expand_flattened_object(object: &mut Map<String, Value>) {
    if object.get("type").and_then(Value::as_str) != Some("object")
        || !object.contains_key("properties")
    {
        return;
    }
    let Some(alternatives) = object.get("oneOf").and_then(Value::as_array) else {
        return;
    };
    if !alternatives.iter().all(|alternative| {
        alternative
            .as_object()
            .and_then(|value| value.get("type"))
            .and_then(Value::as_str)
            == Some("object")
    }) {
        return;
    }

    let base_properties = object
        .remove("properties")
        .and_then(|value| value.as_object().cloned())
        .unwrap_or_default();
    let base_required = object
        .remove("required")
        .and_then(|value| value.as_array().cloned())
        .unwrap_or_default();
    object.remove("type");
    let alternatives = object
        .get_mut("oneOf")
        .and_then(Value::as_array_mut)
        .expect("oneOf was checked above");
    for alternative in alternatives {
        let alternative = alternative
            .as_object_mut()
            .expect("oneOf object alternative was checked above");
        let properties = alternative
            .entry("properties")
            .or_insert_with(|| Value::Object(Map::new()))
            .as_object_mut()
            .expect("object alternative properties must be an object");
        for (key, value) in &base_properties {
            assert!(
                properties.insert(key.clone(), value.clone()).is_none(),
                "flattened schema property {key:?} collides with an enum payload"
            );
        }
        let required = alternative
            .entry("required")
            .or_insert_with(|| Value::Array(Vec::new()))
            .as_array_mut()
            .expect("object alternative required must be an array");
        required.extend(base_required.iter().cloned());
    }
}

fn normalize_typescript(output: String) -> String {
    let mut lines = output.lines().map(str::trim_end).collect::<Vec<_>>();
    while lines.last() == Some(&"") {
        lines.pop();
    }
    lines.join("\n") + "\n"
}

fn push_decl<T: TS>(cfg: &Config, output: &mut String) {
    let decl = T::decl(cfg);
    output.push_str(&export_decl(&decl));
    output.push_str("\n\n");
}

fn export_decl(decl: &str) -> String {
    for prefix in ["type ", "interface ", "enum "] {
        if decl.starts_with(prefix) {
            return format!("export {decl}");
        }
    }
    decl.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn workspace_typescript_omits_runtime_repository_ids() {
        let generated = generated_protocol_types();
        assert!(!generated.contains("repository_id?:"), "{generated}");
        assert!(!generated.contains("repository_id:"), "{generated}");
        assert!(generated.contains("repository_key"), "{generated}");
    }

    #[test]
    fn generated_protocol_types_are_current() {
        let expected = generated_protocol_types();
        let path = generated_typescript_path();
        let actual = std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
        assert_eq!(
            actual, expected,
            "generated TypeScript protocol bindings are stale; run `cargo run -p protocol --example generate_typescript --features typescript`"
        );
    }

    #[test]
    fn generated_protocol_validator_is_current_and_strict() {
        let expected = generated_protocol_validator();
        assert!(expected.contains("\"additionalProperties\":false"));
        assert!(expected.contains("MAX_SUBSCRIPTION_FRAME_JSON_BYTES = 16777216"));
        let path = generated_runtime_validator_path();
        let actual = std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
        assert_eq!(
            actual, expected,
            "generated TypeScript protocol validator is stale; run `cargo run -p protocol --example generate_typescript --features typescript`"
        );
    }
}
