use std::path::PathBuf;

use serde_json::{Map, Value};
use ts_rs::{Config, TS};

use crate::{
    Alert, AlertLevel, AlertSource, CommandEvent, CommandSnapshot, CommandStatus, CommandStream,
    CommandStreamSlice, CompactionLifecycle, CompactionLifecycleState, CompactionPhase,
    CompactionTrigger, CompletionContext, CompletionEntry, CompletionKind, ContextTokenSource,
    ContextUsage, ErrorCode, Event, FeatureInvocation, FeatureInvocationDescriptor,
    FeatureInvocationIdentity, FeatureInvocationResult, FeatureInvocationStatus,
    FeatureInvocationSyntax, Greeting, InFlightBlock, InFlightCompaction, InFlightSnapshot,
    InFlightToolCallState, InternalWorkerKind, InternalWorkerRef, InternalWorkerSnapshot,
    InvocationArgumentDescriptor, InvocationArgumentType, InvocationArgumentValue,
    InvocationClientAdapter, InvocationCompletion, InvocationValue, InvokeKind, MemoryWorkerEvent,
    Method, PasteArtifactAvailability, PasteArtifactMediaType, PasteArtifactRef,
    PendingSubmissionSummary, PendingSubmissionsSnapshot, Permission, ReasoningConfig,
    RewindSummary, RewindTarget, RewindTargetId, RunFailureKind, RunResult, RunResumeSource,
    RunYieldReason, ScopeRule, Segment, SessionContentPart, SessionConversationTurn,
    SessionEntryProvenance, SessionHistoryLineageBoundary, SessionHistoryPage, SessionMessageRole,
    SessionSnapshot, SessionSnapshotEntry, SessionSnapshotEntryData, SessionToolAttachment,
    SubmissionDisposition, SymlinkPolicy, ToolResultDisposition, TurnResult,
    UploadedFileAvailability, UploadedFileRef, WorkerBusyState, WorkerCommandAcknowledgement,
    WorkerCommandDisposition, WorkerCommandEnvelope, WorkerCommandKind, WorkerEvent,
    WorkerMaintenanceState, WorkerRunState, WorkerState, WorkerStateSnapshot, WorkerStatus,
    subscription::{
        EventSubscriptionSelector, MAX_CORRELATION_ID_BYTES, MAX_REJECTION_MESSAGE_BYTES,
        MAX_RESOURCE_ID_BYTES, MAX_SUBSCRIPTION_COLLECTION_ITEMS,
        MAX_SUBSCRIPTION_FRAME_JSON_BYTES, MAX_SUBSCRIPTION_STRING_BYTES,
        MAX_SUBSCRIPTION_VALUE_DEPTH, MAX_SUBSCRIPTION_VALUE_NODES, MAX_WORKER_IDS_PER_SELECTOR,
        SUBSCRIPTION_PROTOCOL_VERSION, SubscriptionEvent, SubscriptionEventPayload,
        SubscriptionFrame, SubscriptionFramePayload, SubscriptionId, SubscriptionRejectionCode,
        SubscriptionRequest, SubscriptionRequestId, SubscriptionResponse, SubscriptionSnapshot,
        SubscriptionTerminationCode, SubscriptionWorkdirId, SubscriptionWorker,
        SubscriptionWorkerAvailability, SubscriptionWorkerId, SubscriptionWorkerIds,
        SubscriptionWorkerJob, SubscriptionWorkerProtocolMethod, SubscriptionWorkerState,
        SubscriptionWorkerWorkdirAttachment, WorkspaceSubscriptionWorkdir,
    },
};

const GENERATED_RELATIVE_PATH: &str = "../../web/workspace/src/lib/generated/protocol.ts";
const GENERATED_VALIDATOR_RELATIVE_PATH: &str =
    "../../web/workspace/src/lib/generated/protocol-validator.ts";

/// Repository-relative destination for the Workspace web protocol bindings.
pub fn generated_typescript_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(GENERATED_RELATIVE_PATH)
}

/// Repository-relative destination for the generated Workspace Browser validator.
pub fn generated_runtime_validator_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(GENERATED_VALIDATOR_RELATIVE_PATH)
}

/// Render Workspace web TypeScript bindings for the Worker wire protocol DTOs.
///
/// Rust DTOs in this crate remain the source of truth; this function is used by
/// both the checked-in artifact generator and the stale-output drift test.
pub fn generated_protocol_types() -> String {
    let cfg = Config::new().with_large_int("number");
    let mut output = String::from(
        "// @generated by `cargo run -p protocol --example generate_typescript --features typescript`\n\
         // Do not edit by hand. Rust DTO authority lives in `crates/protocol`.\n\
         // Large integer fields are JSON numbers on the wire and are emitted as TypeScript `number`.\n\n",
    );

    push_decl::<AlertLevel>(&cfg, &mut output);
    push_decl::<AlertSource>(&cfg, &mut output);
    push_decl::<CompletionKind>(&cfg, &mut output);
    push_decl::<CompletionContext>(&cfg, &mut output);
    push_decl::<FeatureInvocationIdentity>(&cfg, &mut output);
    push_decl::<FeatureInvocationSyntax>(&cfg, &mut output);
    push_decl::<InvocationArgumentType>(&cfg, &mut output);
    push_decl::<InvocationCompletion>(&cfg, &mut output);
    push_decl::<InvocationArgumentDescriptor>(&cfg, &mut output);
    push_decl::<InvocationClientAdapter>(&cfg, &mut output);
    push_decl::<FeatureInvocationDescriptor>(&cfg, &mut output);
    push_decl::<InvocationValue>(&cfg, &mut output);
    push_decl::<InvocationArgumentValue>(&cfg, &mut output);
    push_decl::<FeatureInvocation>(&cfg, &mut output);
    push_decl::<FeatureInvocationStatus>(&cfg, &mut output);
    push_decl::<FeatureInvocationResult>(&cfg, &mut output);
    push_decl::<WorkerStatus>(&cfg, &mut output);
    push_decl::<WorkerCommandEnvelope>(&cfg, &mut output);
    push_decl::<WorkerCommandKind>(&cfg, &mut output);
    push_decl::<WorkerCommandDisposition>(&cfg, &mut output);
    push_decl::<WorkerCommandAcknowledgement>(&cfg, &mut output);
    push_decl::<WorkerRunState>(&cfg, &mut output);
    push_decl::<WorkerMaintenanceState>(&cfg, &mut output);
    push_decl::<WorkerBusyState>(&cfg, &mut output);
    push_decl::<WorkerState>(&cfg, &mut output);
    push_decl::<WorkerStateSnapshot>(&cfg, &mut output);
    push_decl::<TurnResult>(&cfg, &mut output);
    push_decl::<InvokeKind>(&cfg, &mut output);
    push_decl::<RunResult>(&cfg, &mut output);
    push_decl::<ToolResultDisposition>(&cfg, &mut output);
    push_decl::<ErrorCode>(&cfg, &mut output);
    push_decl::<Permission>(&cfg, &mut output);
    push_decl::<SymlinkPolicy>(&cfg, &mut output);
    push_decl::<InFlightToolCallState>(&cfg, &mut output);
    push_decl::<CommandStatus>(&cfg, &mut output);
    push_decl::<CommandStream>(&cfg, &mut output);
    push_decl::<CommandStreamSlice>(&cfg, &mut output);
    push_decl::<CommandSnapshot>(&cfg, &mut output);
    push_decl::<CommandEvent>(&cfg, &mut output);
    push_decl::<CompactionLifecycleState>(&cfg, &mut output);
    push_decl::<CompactionLifecycle>(&cfg, &mut output);
    push_decl::<CompactionPhase>(&cfg, &mut output);
    push_decl::<CompactionTrigger>(&cfg, &mut output);
    push_decl::<UploadedFileAvailability>(&cfg, &mut output);
    push_decl::<UploadedFileRef>(&cfg, &mut output);
    push_decl::<ScopeRule>(&cfg, &mut output);
    push_decl::<CompletionEntry>(&cfg, &mut output);
    push_decl::<RewindTargetId>(&cfg, &mut output);
    push_decl::<RewindTarget>(&cfg, &mut output);
    push_decl::<RewindSummary>(&cfg, &mut output);
    push_decl::<InFlightBlock>(&cfg, &mut output);
    push_decl::<InFlightCompaction>(&cfg, &mut output);
    push_decl::<InFlightSnapshot>(&cfg, &mut output);
    push_decl::<SessionEntryProvenance>(&cfg, &mut output);
    push_decl::<SessionMessageRole>(&cfg, &mut output);
    push_decl::<SessionContentPart>(&cfg, &mut output);
    push_decl::<SessionToolAttachment>(&cfg, &mut output);
    push_decl::<RunYieldReason>(&cfg, &mut output);
    push_decl::<RunResumeSource>(&cfg, &mut output);
    push_decl::<RunFailureKind>(&cfg, &mut output);
    push_decl::<SessionSnapshotEntryData>(&cfg, &mut output);
    push_decl::<SessionSnapshotEntry>(&cfg, &mut output);
    push_decl::<SessionConversationTurn>(&cfg, &mut output);
    push_decl::<SessionHistoryLineageBoundary>(&cfg, &mut output);
    push_decl::<SessionHistoryPage>(&cfg, &mut output);
    push_decl::<PendingSubmissionSummary>(&cfg, &mut output);
    push_decl::<PendingSubmissionsSnapshot>(&cfg, &mut output);
    push_decl::<SubmissionDisposition>(&cfg, &mut output);
    push_decl::<SessionSnapshot>(&cfg, &mut output);
    push_decl::<ReasoningConfig>(&cfg, &mut output);
    push_decl::<ContextTokenSource>(&cfg, &mut output);
    push_decl::<ContextUsage>(&cfg, &mut output);
    push_decl::<Greeting>(&cfg, &mut output);
    push_decl::<InternalWorkerKind>(&cfg, &mut output);
    push_decl::<InternalWorkerRef>(&cfg, &mut output);
    push_decl::<InternalWorkerSnapshot>(&cfg, &mut output);
    push_decl::<Alert>(&cfg, &mut output);
    push_decl::<MemoryWorkerEvent>(&cfg, &mut output);
    push_decl::<PasteArtifactMediaType>(&cfg, &mut output);
    push_decl::<PasteArtifactAvailability>(&cfg, &mut output);
    push_decl::<PasteArtifactRef>(&cfg, &mut output);
    push_decl::<Segment>(&cfg, &mut output);
    push_decl::<WorkerEvent>(&cfg, &mut output);
    push_decl::<SubscriptionRequestId>(&cfg, &mut output);
    push_decl::<SubscriptionId>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerId>(&cfg, &mut output);
    push_decl::<SubscriptionWorkdirId>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerIds>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerState>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerAvailability>(&cfg, &mut output);
    push_decl::<EventSubscriptionSelector>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerWorkdirAttachment>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerJob>(&cfg, &mut output);
    push_decl::<SubscriptionWorker>(&cfg, &mut output);
    push_decl::<WorkspaceSubscriptionWorkdir>(&cfg, &mut output);
    push_decl::<SubscriptionSnapshot>(&cfg, &mut output);
    push_decl::<SubscriptionEventPayload>(&cfg, &mut output);
    push_decl::<SubscriptionRejectionCode>(&cfg, &mut output);
    push_decl::<SubscriptionTerminationCode>(&cfg, &mut output);
    push_decl::<SubscriptionRequest>(&cfg, &mut output);
    push_decl::<SubscriptionWorkerProtocolMethod>(&cfg, &mut output);
    push_decl::<SubscriptionResponse>(&cfg, &mut output);
    push_decl::<SubscriptionEvent>(&cfg, &mut output);
    push_decl::<SubscriptionFramePayload>(&cfg, &mut output);
    push_decl::<SubscriptionFrame>(&cfg, &mut output);
    push_decl::<Method>(&cfg, &mut output);
    push_decl::<Event>(&cfg, &mut output);

    normalize_typescript(output)
}

/// Render the strict runtime validator paired with the generated declarations.
///
/// `schemars` projects the reachable Serde shape from [`SubscriptionFrame`]. The
/// normalization closes every object and expands flattened enum payloads before
/// embedding that schema into the dependency-free Browser validator template.
pub fn generated_protocol_validator() -> String {
    let mut schema = serde_json::to_value(schemars::schema_for!(SubscriptionFrame))
        .expect("SubscriptionFrame schema must serialize");
    close_object_shapes(&mut schema);
    let schema = serde_json::to_string(&schema).expect("SubscriptionFrame schema must serialize");
    let fixtures = serde_json::to_string(&rust_serialized_subscription_frame_fixtures())
        .expect("SubscriptionFrame fixtures must serialize");
    include_str!("typescript_validator_template.ts")
        .replace(
            "__GENERATED_PREAMBLE__",
            "// @generated by `cargo run -p protocol --example generate_typescript --features typescript`\n// Do not edit by hand. Rust DTO and validation authority lives in `crates/protocol`.",
        )
        .replace(
            "__PROTOCOL_VERSION__",
            &SUBSCRIPTION_PROTOCOL_VERSION.to_string(),
        )
        .replace(
            "__MAX_FRAME_BYTES__",
            &MAX_SUBSCRIPTION_FRAME_JSON_BYTES.to_string(),
        )
        .replace(
            "__MAX_STRING_BYTES__",
            &MAX_SUBSCRIPTION_STRING_BYTES.to_string(),
        )
        .replace(
            "__MAX_COLLECTION_ITEMS__",
            &MAX_SUBSCRIPTION_COLLECTION_ITEMS.to_string(),
        )
        .replace(
            "__MAX_VALUE_DEPTH__",
            &MAX_SUBSCRIPTION_VALUE_DEPTH.to_string(),
        )
        .replace(
            "__MAX_VALUE_NODES__",
            &MAX_SUBSCRIPTION_VALUE_NODES.to_string(),
        )
        .replace(
            "__MAX_CORRELATION_ID_BYTES__",
            &MAX_CORRELATION_ID_BYTES.to_string(),
        )
        .replace(
            "__MAX_RESOURCE_ID_BYTES__",
            &MAX_RESOURCE_ID_BYTES.to_string(),
        )
        .replace(
            "__MAX_WORKER_IDS_PER_SELECTOR__",
            &MAX_WORKER_IDS_PER_SELECTOR.to_string(),
        )
        .replace(
            "__MAX_REJECTION_MESSAGE_BYTES__",
            &MAX_REJECTION_MESSAGE_BYTES.to_string(),
        )
        .replace("__SUBSCRIPTION_FRAME_SCHEMA__", &schema)
        .replace("__RUST_SERIALIZED_FIXTURES__", &fixtures)
}

fn rust_serialized_subscription_frame_fixtures() -> Vec<SubscriptionFrame> {
    let request_id =
        SubscriptionRequestId::new("fixture-request").expect("fixture request id must be valid");
    let subscription_id =
        SubscriptionId::new("fixture-subscription").expect("fixture subscription id must be valid");
    let worker_id =
        SubscriptionWorkerId::new("fixture-worker").expect("fixture worker id must be valid");
    let external_workdir_id = SubscriptionWorkdirId::new("fixture-external-workdir")
        .expect("fixture external Workdir id must be valid");
    let worker = SubscriptionWorker {
        restore_observation_token: Some("fixture-restore-observation".into()),
        worker_id: worker_id.clone(),
        runtime_id: Some("fixture-runtime".to_string()),
        resource_key: Some("fixture-worker-resource".to_string()),
        availability: SubscriptionWorkerAvailability::default(),
        worker_state: None,
        state: SubscriptionWorkerState::Idle,
        has_running_internal_workers: false,
        workspace_id: Some("fixture-workspace".to_string()),
        display_name: None,
        profile: None,
        job: None,
        workdir_attachments: vec![SubscriptionWorkerWorkdirAttachment {
            alias: "external".to_string(),
            repository_id: None,
            repository_key: None,
            working_directory_id: external_workdir_id,
        }],
    };
    let subscribed = SubscriptionFrame::new(SubscriptionFramePayload::Response(
        SubscriptionResponse::Subscribed {
            request_id,
            subscription_id: subscription_id.clone(),
            selector: EventSubscriptionSelector::WorkspaceWorkers,
            snapshot: SubscriptionSnapshot::Workers {
                workers: vec![worker],
            },
        },
    ));
    let pending =
        SubscriptionFrame::new(SubscriptionFramePayload::Event(SubscriptionEvent::Event {
            subscription_id: subscription_id.clone(),
            payload: SubscriptionEventPayload::WorkerProtocol {
                worker_id: worker_id.clone(),
                event: Event::PendingSubmissionsChanged {
                    pending: PendingSubmissionsSnapshot::default(),
                },
            },
        }));
    let greeting = Greeting {
        worker_name: "fixture-worker".into(),
        cwd: "/fixture".into(),
        provider: "openai_responses".into(),
        model: "gpt-6-astra".into(),
        reasoning: Some(ReasoningConfig::Effort {
            effort: "high".into(),
        }),
        scope_summary: "fixture scope".into(),
        tools: vec!["Read".into()],
        context_window: 272_000,
        context_tokens: 142_000,
        context_usage: Some(ContextUsage {
            tokens: 142_000,
            source: ContextTokenSource::Measured,
        }),
    };
    let snapshot =
        SubscriptionFrame::new(SubscriptionFramePayload::Event(SubscriptionEvent::Event {
            subscription_id,
            payload: SubscriptionEventPayload::WorkerProtocol {
                worker_id,
                event: Event::Snapshot {
                    session: SessionSnapshot {
                        pending_submissions: PendingSubmissionsSnapshot::default(),
                        entries: Vec::new(),
                    },
                    greeting: greeting.clone(),
                    state: WorkerStateSnapshot::initial(),
                    in_flight: InFlightSnapshot::default(),
                    internal_workers: vec![InternalWorkerSnapshot {
                        worker: InternalWorkerRef {
                            session_id: "fixture-child-session".into(),
                            name: "fixture-child".into(),
                            parent_session_id: Some("fixture-parent-session".into()),
                            kind: InternalWorkerKind::SubWorker,
                        },
                        revision: 1,
                        session: SessionSnapshot {
                            pending_submissions: PendingSubmissionsSnapshot::default(),
                            entries: Vec::new(),
                        },
                        greeting: Some(greeting),
                        status: WorkerStatus::Idle,
                        error: None,
                        in_flight: InFlightSnapshot::default(),
                        internal_workers: Vec::new(),
                    }],
                },
            },
        }));
    for fixture in [&subscribed, &pending, &snapshot] {
        fixture
            .validate()
            .expect("Rust-serialized Browser compatibility fixture must validate");
    }
    vec![subscribed, pending, snapshot]
}

fn close_object_shapes(schema: &mut Value) {
    let Value::Object(object) = schema else {
        if let Value::Array(values) = schema {
            for value in values {
                close_object_shapes(value);
            }
        }
        return;
    };

    expand_flattened_object(object);
    for value in object.values_mut() {
        close_object_shapes(value);
    }
    normalize_null_default(object);
    normalize_integer_format(object);
    require_serialized_defaults(object);
    if object.get("type").and_then(Value::as_str) == Some("object")
        && object.contains_key("properties")
    {
        object.insert("additionalProperties".to_string(), Value::Bool(false));
    }
}

fn normalize_null_default(schema: &mut Map<String, Value>) {
    if schema.get("default") != Some(&Value::Null) || schema.contains_key("anyOf") {
        return;
    }
    let Some(schema_type) = schema.get_mut("type") else {
        return;
    };
    match schema_type {
        Value::String(value) if value != "null" => {
            *schema_type = Value::Array(vec![
                Value::String(value.clone()),
                Value::String("null".into()),
            ]);
        }
        Value::Array(values) if !values.iter().any(|value| value.as_str() == Some("null")) => {
            values.push(Value::String("null".into()));
        }
        _ => {}
    }
}

fn normalize_integer_format(schema: &mut Map<String, Value>) {
    let is_integer = match schema.get("type") {
        Some(Value::String(value)) => value == "integer",
        Some(Value::Array(values)) => values.iter().any(|value| value.as_str() == Some("integer")),
        _ => false,
    };
    if !is_integer {
        return;
    }
    let Some(format) = schema.get("format").and_then(Value::as_str) else {
        return;
    };
    let (minimum, maximum) = match format {
        "uint16" => (0.0, u16::MAX as f64),
        "uint32" => (0.0, u32::MAX as f64),
        "uint" | "uint64" => (0.0, 9_007_199_254_740_991.0),
        "int32" => (i32::MIN as f64, i32::MAX as f64),
        "int64" => (-9_007_199_254_740_991.0, 9_007_199_254_740_991.0),
        other => panic!("unsupported integer format in SubscriptionFrame schema: {other}"),
    };
    tighten_numeric_bound(schema, "minimum", minimum, f64::max);
    tighten_numeric_bound(schema, "maximum", maximum, f64::min);
}

fn tighten_numeric_bound(
    schema: &mut Map<String, Value>,
    keyword: &str,
    contract_bound: f64,
    tighten: fn(f64, f64) -> f64,
) {
    let bound = schema
        .get(keyword)
        .and_then(Value::as_f64)
        .map_or(contract_bound, |existing| tighten(existing, contract_bound));
    schema.insert(
        keyword.to_string(),
        Value::Number(serde_json::Number::from_f64(bound).expect("finite JSON Schema bound")),
    );
}

fn require_serialized_defaults(schema: &mut Map<String, Value>) {
    if schema.get("type").and_then(Value::as_str) != Some("object") {
        return;
    }
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        return;
    };
    let defaulted = properties
        .iter()
        .filter(|(_, property)| {
            property
                .as_object()
                .is_some_and(|value| value.contains_key("default"))
        })
        .map(|(key, _)| Value::String(key.clone()))
        .collect::<Vec<_>>();
    if defaulted.is_empty() {
        return;
    }
    let required = schema
        .entry("required")
        .or_insert_with(|| Value::Array(Vec::new()))
        .as_array_mut()
        .expect("object required must be an array");
    for key in defaulted {
        if !required.contains(&key) {
            required.push(key);
        }
    }
}

/// Serde flatten is represented by schemars as object properties beside `oneOf`.
/// Move those common properties into each object alternative so standard JSON
/// Schema `additionalProperties: false` has the intended exact-shape semantics.
fn expand_flattened_object(object: &mut Map<String, Value>) {
    if object.get("type").and_then(Value::as_str) != Some("object")
        || !object.contains_key("properties")
    {
        return;
    }
    let Some(alternatives) = object.get("oneOf").and_then(Value::as_array) else {
        return;
    };
    if !alternatives.iter().all(|alternative| {
        alternative
            .as_object()
            .and_then(|value| value.get("type"))
            .and_then(Value::as_str)
            == Some("object")
    }) {
        return;
    }

    let base_properties = object
        .remove("properties")
        .and_then(|value| value.as_object().cloned())
        .unwrap_or_default();
    let base_required = object
        .remove("required")
        .and_then(|value| value.as_array().cloned())
        .unwrap_or_default();
    object.remove("type");
    let alternatives = object
        .get_mut("oneOf")
        .and_then(Value::as_array_mut)
        .expect("oneOf was checked above");
    for alternative in alternatives {
        let alternative = alternative
            .as_object_mut()
            .expect("oneOf object alternative was checked above");
        let properties = alternative
            .entry("properties")
            .or_insert_with(|| Value::Object(Map::new()))
            .as_object_mut()
            .expect("object alternative properties must be an object");
        for (key, value) in &base_properties {
            assert!(
                properties.insert(key.clone(), value.clone()).is_none(),
                "flattened schema property {key:?} collides with an enum payload"
            );
        }
        let required = alternative
            .entry("required")
            .or_insert_with(|| Value::Array(Vec::new()))
            .as_array_mut()
            .expect("object alternative required must be an array");
        required.extend(base_required.iter().cloned());
    }
}

fn normalize_typescript(output: String) -> String {
    let mut lines = output.lines().map(str::trim_end).collect::<Vec<_>>();
    while lines.last() == Some(&"") {
        lines.pop();
    }
    lines.join("\n") + "\n"
}

fn push_decl<T: TS>(cfg: &Config, output: &mut String) {
    let decl = T::decl(cfg);
    output.push_str(&export_decl(&decl));
    output.push_str("\n\n");
}

fn export_decl(decl: &str) -> String {
    for prefix in ["type ", "interface ", "enum "] {
        if decl.starts_with(prefix) {
            return format!("export {decl}");
        }
    }
    decl.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn workspace_typescript_omits_runtime_repository_ids() {
        let generated = generated_protocol_types();
        assert!(!generated.contains("repository_id?:"), "{generated}");
        assert!(!generated.contains("repository_id:"), "{generated}");
        assert!(generated.contains("repository_key"), "{generated}");
    }

    #[test]
    fn generated_schema_matches_serialized_defaults_and_rust_integer_widths() {
        let mut schema = serde_json::to_value(schemars::schema_for!(SubscriptionFrame)).unwrap();
        close_object_shapes(&mut schema);

        let worker_required = schema
            .pointer("/$defs/SubscriptionWorker/required")
            .and_then(Value::as_array)
            .unwrap();
        assert!(worker_required.contains(&Value::String("availability".into())));
        assert!(worker_required.contains(&Value::String("has_running_internal_workers".into())));

        let pending_required = schema
            .pointer("/$defs/PendingSubmissionsSnapshot/required")
            .and_then(Value::as_array)
            .unwrap();
        for field in ["notification_count", "head_id", "submissions"] {
            assert!(pending_required.contains(&Value::String(field.into())));
        }
        assert_eq!(
            schema.pointer("/$defs/PendingSubmissionsSnapshot/properties/head_id/type"),
            Some(&serde_json::json!(["string", "null"]))
        );
        assert!(
            generated_protocol_validator().contains("\"format\":\"uint32\",\"maximum\":4294967295")
        );
    }

    #[test]
    #[should_panic(expected = "unsupported integer format")]
    fn generated_schema_rejects_unknown_integer_formats() {
        let mut unsupported = serde_json::json!({"type": "integer", "format": "uint128"});
        close_object_shapes(&mut unsupported);
    }

    #[test]
    fn generated_protocol_types_are_current() {
        let expected = generated_protocol_types();
        let path = generated_typescript_path();
        let actual = std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
        assert_eq!(
            actual, expected,
            "generated TypeScript protocol bindings are stale; run `cargo run -p protocol --example generate_typescript --features typescript`"
        );
    }

    #[test]
    fn generated_protocol_validator_is_current_and_strict() {
        let expected = generated_protocol_validator();
        assert!(expected.contains("\"additionalProperties\":false"));
        assert!(expected.contains("MAX_SUBSCRIPTION_FRAME_JSON_BYTES = 16777216"));
        let path = generated_runtime_validator_path();
        let actual = std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
        assert_eq!(
            actual, expected,
            "generated TypeScript protocol validator is stale; run `cargo run -p protocol --example generate_typescript --features typescript`"
        );
    }
}
