use std::collections::{BTreeMap, BTreeSet};

use serde_json::{Map, Value};

pub const GENERATOR_NAME: &str = "yoi-repository-openapi-typescript";
pub const GENERATOR_VERSION: &str = "1";
pub const GENERATOR_OPTIONS: &str = "repository-operation-schema-closure,openapi-3.1,format:uint64=safe-number,strict-safe-integers,sorted-output";
pub const INPUT_PATH: &str = "openapi/server-api.json";
pub const OUTPUT_PATH: &str = "web/workspace/src/lib/generated/repository-api.ts";
pub const WORKDIR_GENERATOR_NAME: &str = "yoi-workdir-openapi-typescript";
pub const WORKDIR_GENERATOR_VERSION: &str = "1";
pub const WORKDIR_GENERATOR_OPTIONS: &str =
    "workdir-operation-schema-closure,openapi-3.1,strict-integer-ranges,sorted-output";
pub const WORKDIR_OUTPUT_PATH: &str = "web/workspace/src/lib/generated/workdir-api.ts";

const MAX_SAFE_INTEGER: f64 = 9_007_199_254_740_991.0;
const MIN_SAFE_INTEGER: f64 = -9_007_199_254_740_991.0;
const SCHEMA_REF_PREFIX: &str = "#/components/schemas/";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerationError(String);

impl GenerationError {
    fn invalid(message: impl Into<String>) -> Self {
        Self(message.into())
    }
}

impl std::fmt::Display for GenerationError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl std::error::Error for GenerationError {}

pub fn generate_repository_typescript(input: &str) -> Result<String, GenerationError> {
    let document: Value = serde_json::from_str(input)
        .map_err(|error| GenerationError::invalid(format!("invalid OpenAPI JSON: {error}")))?;
    let root = object(&document, "OpenAPI document")?;
    if root.get("openapi").and_then(Value::as_str) != Some("3.1.0") {
        return Err(GenerationError::invalid(
            "Repository TypeScript generation requires OpenAPI 3.1.0",
        ));
    }

    let info = object_field(root, "info", "OpenAPI document")?;
    let contract_version = required_string(info, "version", "OpenAPI info")?;
    let contract_digest = required_string(info, "x-yoi-source-digest", "OpenAPI info")?;
    validate_contract_digest(contract_digest)?;

    let schemas = object_field(
        object_field(root, "components", "OpenAPI document")?,
        "schemas",
        "OpenAPI components",
    )?;
    let paths = object_field(root, "paths", "OpenAPI document")?;
    let roots = validate_repository_operations(paths)?;
    let closure = schema_closure(schemas, &roots)?;

    let mut output = format!(
        "// @generated by {GENERATOR_NAME}@{GENERATOR_VERSION}. Do not edit.\n\
// Input: {INPUT_PATH}\n\
// Input contract: {contract_version} ({contract_digest})\n\
// Options: {GENERATOR_OPTIONS}\n\
// Output: {OUTPUT_PATH}\n\
// Regenerate/check: cargo run -q -p server-api --example generate_repository_openapi_types -- --check\n\n"
    );
    for name in closure {
        let schema = schemas
            .get(&name)
            .ok_or_else(|| GenerationError::invalid(format!("missing schema `{name}`")))?;
        let declaration = render_schema(schema, &format!("schema `{name}`"))?;
        output.push_str(&format!("export type {name} = {declaration};\n\n"));
    }
    output.pop();
    Ok(output)
}

pub fn generate_workdir_typescript(input: &str) -> Result<String, GenerationError> {
    let document: Value = serde_json::from_str(input)
        .map_err(|error| GenerationError::invalid(format!("invalid OpenAPI JSON: {error}")))?;
    let root = object(&document, "OpenAPI document")?;
    if root.get("openapi").and_then(Value::as_str) != Some("3.1.0") {
        return Err(GenerationError::invalid(
            "Workdir TypeScript generation requires OpenAPI 3.1.0",
        ));
    }

    let info = object_field(root, "info", "OpenAPI document")?;
    let contract_version = required_string(info, "version", "OpenAPI info")?;
    let contract_digest = required_string(info, "x-yoi-source-digest", "OpenAPI info")?;
    validate_contract_digest(contract_digest)?;
    let schemas = object_field(
        object_field(root, "components", "OpenAPI document")?,
        "schemas",
        "OpenAPI components",
    )?;
    let paths = object_field(root, "paths", "OpenAPI document")?;
    let roots = validate_workdir_operations(paths)?;
    let closure = schema_closure(schemas, &roots)?;

    let mut output = format!(
        "// @generated by {WORKDIR_GENERATOR_NAME}@{WORKDIR_GENERATOR_VERSION}. Do not edit.\n\
// Input: {INPUT_PATH}\n\
// Input contract: {contract_version} ({contract_digest})\n\
// Options: {WORKDIR_GENERATOR_OPTIONS}\n\
// Output: {WORKDIR_OUTPUT_PATH}\n\
// Regenerate/check: cargo run -q -p server-api --example generate_workdir_api_types -- --check\n\n"
    );
    for name in closure {
        let schema = schemas
            .get(&name)
            .ok_or_else(|| GenerationError::invalid(format!("missing schema `{name}`")))?;
        let declaration = render_schema(schema, &format!("schema `{name}`"))?;
        output.push_str(&format!("export type {name} = {declaration};\n\n"));
    }
    output.pop();
    Ok(output)
}

fn validate_contract_digest(digest: &str) -> Result<(), GenerationError> {
    let Some(hex) = digest.strip_prefix("sha256:") else {
        return Err(GenerationError::invalid(
            "OpenAPI source digest must use sha256",
        ));
    };
    if hex.len() != 64 || !hex.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(GenerationError::invalid(
            "OpenAPI source digest must contain 64 hexadecimal digits",
        ));
    }
    Ok(())
}

fn validate_repository_operations(
    paths: &Map<String, Value>,
) -> Result<BTreeSet<String>, GenerationError> {
    let operations = [
        OperationContract {
            path: "/api/repositories",
            method: "get",
            operation_id: "repository_list_alias",
            request: None,
            successes: &[("200", "RepositoryListResponse")],
        },
        OperationContract {
            path: "/api/repositories/{repository_key}",
            method: "get",
            operation_id: "repository_detail_alias",
            request: None,
            successes: &[("200", "RepositoryDetailResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/repositories",
            method: "get",
            operation_id: "repository_list",
            request: None,
            successes: &[("200", "RepositoryListResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/repositories",
            method: "post",
            operation_id: "repository_create",
            request: Some("CreateWorkspaceRepositoryRequest"),
            successes: &[
                ("200", "CreateWorkspaceRepositoryResponse"),
                ("201", "CreateWorkspaceRepositoryResponse"),
            ],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/repositories/{repository_key}",
            method: "get",
            operation_id: "repository_detail",
            request: None,
            successes: &[("200", "RepositoryDetailResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/repositories/{repository_key}/ssh-connection-test",
            method: "post",
            operation_id: "repository_ssh_connection_probe",
            request: Some("RepositorySshConnectionProbeRequest"),
            successes: &[("200", "RepositorySshConnectionProbeResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/repositories/{repository_key}/ssh-connection-test",
            method: "put",
            operation_id: "repository_ssh_host_trust_confirm",
            request: Some("ConfirmRepositorySshHostTrustRequest"),
            successes: &[("200", "RepositorySshHostTrust")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/repositories/{repository_key}/log",
            method: "get",
            operation_id: "repository_log",
            request: None,
            successes: &[("200", "RepositoryLogResponse")],
        },
        OperationContract {
            path: "/api/repositories/{repository_key}/log",
            method: "get",
            operation_id: "repository_log_alias",
            request: None,
            successes: &[("200", "RepositoryLogResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/hosts",
            method: "get",
            operation_id: "host_list",
            request: None,
            successes: &[("200", "HostListResponse")],
        },
        OperationContract {
            path: "/api/hosts",
            method: "get",
            operation_id: "host_list_alias",
            request: None,
            successes: &[("200", "HostListResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/hosts/{host_id}/workers",
            method: "get",
            operation_id: "host_worker_list",
            request: None,
            successes: &[("200", "HostWorkerListResponse")],
        },
        OperationContract {
            path: "/api/hosts/{host_id}/workers",
            method: "get",
            operation_id: "host_worker_list_alias",
            request: None,
            successes: &[("200", "HostWorkerListResponse")],
        },
    ];
    validate_operation_contracts(paths, &operations)
}

fn validate_workdir_operations(
    paths: &Map<String, Value>,
) -> Result<BTreeSet<String>, GenerationError> {
    let operations = [
        OperationContract {
            path: "/api/w/{workspace_id}/runtimes/{runtime_id}/working-directories",
            method: "get",
            operation_id: "runtime_workdir_list",
            request: None,
            successes: &[("200", "WorkingDirectoryListResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/runtimes/{runtime_id}/working-directories",
            method: "post",
            operation_id: "runtime_workdir_create",
            request: Some("WorkingDirectoryCreateRequest"),
            successes: &[
                ("200", "WorkingDirectoryCreateResponse"),
                ("201", "WorkingDirectoryCreateResponse"),
            ],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/runtimes/{runtime_id}/working-directories/{working_directory_id}",
            method: "get",
            operation_id: "runtime_workdir_detail",
            request: None,
            successes: &[("200", "WorkingDirectoryDetailResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/runtimes/{runtime_id}/working-directories/{working_directory_id}",
            method: "delete",
            operation_id: "runtime_workdir_cleanup",
            request: Some("WorkingDirectoryRemovalRequest"),
            successes: &[("200", "WorkingDirectoryRemovalResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/workers/self/workdir-attachments",
            method: "post",
            operation_id: "current_worker_workdir_attach",
            request: Some("CurrentWorkerWorkdirAttachRequest"),
            successes: &[("200", "CurrentWorkerWorkdirAttachmentResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/workers/self/workdir-attachments/{alias}",
            method: "delete",
            operation_id: "current_worker_workdir_detach",
            request: None,
            successes: &[("200", "CurrentWorkerWorkdirAttachmentResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/workers/self/workdir-session/operations",
            method: "post",
            operation_id: "current_worker_workdir_operation",
            request: Some("CurrentWorkerWorkdirOperationRequest"),
            successes: &[("200", "WorkdirSessionOperationResult")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/external-workdir-grants",
            method: "post",
            operation_id: "external_workdir_grant_create",
            request: Some("ExternalWorkdirGrantCreateRequest"),
            successes: &[("201", "ExternalWorkdirGrantResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/external-workdir-grants/{grant_id}",
            method: "get",
            operation_id: "external_workdir_grant_get",
            request: None,
            successes: &[("200", "ExternalWorkdirGrantResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/external-workdir-grants/{grant_id}",
            method: "delete",
            operation_id: "external_workdir_grant_revoke",
            request: None,
            successes: &[("200", "ExternalWorkdirGrantResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/working-directories",
            method: "get",
            operation_id: "workspace_workdir_list",
            request: None,
            successes: &[("200", "WorkingDirectoryListResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/working-directories",
            method: "post",
            operation_id: "workspace_workdir_create",
            request: Some("WorkingDirectoryCreateRequest"),
            successes: &[
                ("200", "WorkingDirectoryCreateResponse"),
                ("201", "WorkingDirectoryCreateResponse"),
            ],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/working-directories/{working_directory_id}",
            method: "get",
            operation_id: "workspace_workdir_detail",
            request: None,
            successes: &[("200", "WorkingDirectoryDetailResponse")],
        },
        OperationContract {
            path: "/api/w/{workspace_id}/working-directories/{working_directory_id}",
            method: "delete",
            operation_id: "workspace_workdir_cleanup",
            request: Some("WorkingDirectoryRemovalRequest"),
            successes: &[("200", "WorkingDirectoryRemovalResponse")],
        },
    ];
    validate_operation_contracts(paths, &operations)
}

fn validate_operation_contracts(
    paths: &Map<String, Value>,
    operations: &[OperationContract],
) -> Result<BTreeSet<String>, GenerationError> {
    let mut roots = BTreeSet::new();
    for operation in operations {
        let path = object_field(paths, operation.path, "OpenAPI paths")?;
        let value = object_field(path, operation.method, operation.path)?;
        if value.get("operationId").and_then(Value::as_str) != Some(operation.operation_id) {
            return Err(GenerationError::invalid(format!(
                "{} {} must retain operationId `{}`",
                operation.method, operation.path, operation.operation_id
            )));
        }

        match operation.request {
            Some(expected) => {
                let request = object_field(value, "requestBody", operation.operation_id)?;
                let schema = json_content_schema(request, operation.operation_id)?;
                require_schema_ref(schema, expected, operation.operation_id)?;
                roots.insert(expected.to_owned());
            }
            None if value.contains_key("requestBody") => {
                return Err(GenerationError::invalid(format!(
                    "{} unexpectedly gained a request body",
                    operation.operation_id
                )));
            }
            None => {}
        }

        let responses = object_field(value, "responses", operation.operation_id)?;
        let successes = operation
            .successes
            .iter()
            .copied()
            .collect::<BTreeMap<_, _>>();
        for (status, response) in responses {
            let response = object(
                response,
                &format!("{} response {status}", operation.operation_id),
            )?;
            let schema = json_content_schema(response, operation.operation_id)?;
            let expected = successes.get(status.as_str()).copied().unwrap_or_else(|| {
                if operation.operation_id == "current_worker_workdir_operation" {
                    "WorkdirOperationApiError"
                } else {
                    "RepositoryApiError"
                }
            });
            require_schema_ref(schema, expected, operation.operation_id)?;
            roots.insert(expected.to_owned());
        }
        for (status, expected) in successes {
            if !responses.contains_key(status) {
                return Err(GenerationError::invalid(format!(
                    "{} is missing success response {status} ({expected})",
                    operation.operation_id
                )));
            }
        }
    }
    Ok(roots)
}

struct OperationContract {
    path: &'static str,
    method: &'static str,
    operation_id: &'static str,
    request: Option<&'static str>,
    successes: &'static [(&'static str, &'static str)],
}

fn json_content_schema<'a>(
    value: &'a Map<String, Value>,
    context: &str,
) -> Result<&'a Value, GenerationError> {
    object_field(
        object_field(value, "content", context)?,
        "application/json",
        context,
    )?
    .get("schema")
    .ok_or_else(|| GenerationError::invalid(format!("{context} is missing its JSON schema")))
}

fn schema_reference<'a>(value: &'a Value, context: &str) -> Result<&'a str, GenerationError> {
    const ALLOWED_REFERENCE_SIBLINGS: &[&str] =
        &["$ref", "$comment", "deprecated", "description", "title"];
    let schema = object(value, context)?;
    if let Some(keyword) = schema
        .keys()
        .find(|keyword| !ALLOWED_REFERENCE_SIBLINGS.contains(&keyword.as_str()))
    {
        return Err(GenerationError::invalid(format!(
            "{context} contains unsupported `$ref` sibling `{keyword}`"
        )));
    }
    schema.get("$ref").and_then(Value::as_str).ok_or_else(|| {
        GenerationError::invalid(format!("{context} must use a string schema reference"))
    })
}

fn require_schema_ref(value: &Value, expected: &str, context: &str) -> Result<(), GenerationError> {
    let reference = schema_reference(value, context)?;
    if reference != format!("{SCHEMA_REF_PREFIX}{expected}") {
        return Err(GenerationError::invalid(format!(
            "{context} must reference `{expected}`, found `{reference}`"
        )));
    }
    Ok(())
}

fn schema_closure(
    schemas: &Map<String, Value>,
    roots: &BTreeSet<String>,
) -> Result<BTreeSet<String>, GenerationError> {
    let mut closure = BTreeSet::new();
    let mut pending = roots.iter().cloned().collect::<Vec<_>>();
    while let Some(name) = pending.pop() {
        if !closure.insert(name.clone()) {
            continue;
        }
        let schema = schemas.get(&name).ok_or_else(|| {
            GenerationError::invalid(format!("OpenAPI schema `{name}` is missing"))
        })?;
        let mut references = BTreeSet::new();
        collect_schema_references(schema, &name, &mut references)?;
        pending.extend(references);
    }
    Ok(closure)
}

fn collect_schema_references(
    value: &Value,
    context: &str,
    references: &mut BTreeSet<String>,
) -> Result<(), GenerationError> {
    match value {
        Value::Object(object) => {
            if object.contains_key("$ref") {
                let reference = schema_reference(value, context)?;
                let Some(name) = reference.strip_prefix(SCHEMA_REF_PREFIX) else {
                    return Err(GenerationError::invalid(format!(
                        "{context} contains unsupported reference `{reference}`"
                    )));
                };
                references.insert(name.to_owned());
            }
            for value in object.values() {
                collect_schema_references(value, context, references)?;
            }
        }
        Value::Array(values) => {
            for value in values {
                collect_schema_references(value, context, references)?;
            }
        }
        _ => {}
    }
    Ok(())
}

fn ensure_schema_keywords(
    schema: &Map<String, Value>,
    allowed: &[&str],
    context: &str,
) -> Result<(), GenerationError> {
    const ALLOWED_ANNOTATIONS: &[&str] = &[
        "$comment",
        "default",
        "deprecated",
        "description",
        "example",
        "examples",
        "title",
    ];
    if let Some(keyword) = schema.keys().find(|keyword| {
        !allowed.contains(&keyword.as_str()) && !ALLOWED_ANNOTATIONS.contains(&keyword.as_str())
    }) {
        return Err(GenerationError::invalid(format!(
            "{context} contains unsupported schema keyword `{keyword}`"
        )));
    }
    Ok(())
}

fn literal_matches_type(kind: &str, value: &Value) -> bool {
    matches!(
        (kind, value),
        ("string", Value::String(_)) | ("boolean", Value::Bool(_)) | ("null", Value::Null)
    )
}

fn tagged_object_discriminator(value: &Value) -> Option<(String, String)> {
    let schema = value.as_object()?;
    if schema.get("type")?.as_str()? != "object"
        || schema.get("additionalProperties") != Some(&Value::Bool(false))
    {
        return None;
    }
    let required = schema.get("required")?.as_array()?;
    let properties = schema.get("properties")?.as_object()?;
    properties.iter().find_map(|(name, property)| {
        if !required
            .iter()
            .any(|required| required.as_str() == Some(name))
        {
            return None;
        }
        let literal = property.as_object()?.get("const")?.as_str()?;
        Some((name.clone(), literal.to_owned()))
    })
}

fn literal_schema_matches_type(schema: &Map<String, Value>, kind: &str) -> bool {
    if let Some(constant) = schema.get("const") {
        return literal_matches_type(kind, constant);
    }
    schema
        .get("enum")
        .and_then(Value::as_array)
        .is_some_and(|values| {
            !values.is_empty() && values.iter().all(|value| literal_matches_type(kind, value))
        })
}

fn render_schema(value: &Value, context: &str) -> Result<String, GenerationError> {
    if value == &Value::Bool(true) {
        return Ok("unknown".to_owned());
    }
    if value == &Value::Bool(false) {
        return Err(GenerationError::invalid(format!(
            "{context} rejects every value"
        )));
    }
    let schema = object(value, context)?;
    if schema.contains_key("$ref") {
        let reference = schema_reference(value, context)?;
        return reference
            .strip_prefix(SCHEMA_REF_PREFIX)
            .map(str::to_owned)
            .ok_or_else(|| {
                GenerationError::invalid(format!(
                    "{context} contains unsupported reference `{reference}`"
                ))
            });
    }
    if let Some(constant) = schema.get("const") {
        ensure_schema_keywords(schema, &["const", "type"], context)?;
        if let Some(type_value) = schema.get("type") {
            let kind = type_value.as_str().ok_or_else(|| {
                GenerationError::invalid(format!("{context} const type must be a string"))
            })?;
            if !literal_matches_type(kind, constant) {
                return Err(GenerationError::invalid(format!(
                    "{context} const literal does not match type `{kind}`"
                )));
            }
        }
        return render_literal(constant, context);
    }
    if let Some(enumeration) = schema.get("enum") {
        ensure_schema_keywords(schema, &["enum", "type"], context)?;
        let values = enumeration.as_array().ok_or_else(|| {
            GenerationError::invalid(format!("{context} contains a non-array enum"))
        })?;
        if values.is_empty() {
            return Err(GenerationError::invalid(format!(
                "{context} contains an empty enum"
            )));
        }
        if let Some(type_value) = schema.get("type") {
            let kind = type_value.as_str().ok_or_else(|| {
                GenerationError::invalid(format!("{context} enum type must be a string"))
            })?;
            if !values.iter().all(|value| literal_matches_type(kind, value)) {
                return Err(GenerationError::invalid(format!(
                    "{context} enum literals do not match type `{kind}`"
                )));
            }
        }
        return values
            .iter()
            .map(|value| render_literal(value, context))
            .collect::<Result<Vec<_>, _>>()
            .map(|values| values.join(" | "));
    }
    if let Some(branches) = schema.get("anyOf") {
        ensure_schema_keywords(schema, &["anyOf"], context)?;
        return render_nullable_union(branches, context);
    }
    if let Some(branches) = schema.get("oneOf") {
        ensure_schema_keywords(schema, &["oneOf", "type"], context)?;
        let outer_type = match schema.get("type") {
            Some(Value::String(kind)) if kind == "string" => Some(kind.as_str()),
            Some(_) => {
                return Err(GenerationError::invalid(format!(
                    "{context} contains an unsupported oneOf type"
                )));
            }
            None => None,
        };
        let branches = branches.as_array().ok_or_else(|| {
            GenerationError::invalid(format!("{context} contains a non-array oneOf"))
        })?;
        if branches.is_empty() {
            return Err(GenerationError::invalid(format!(
                "{context} contains an empty oneOf"
            )));
        }
        let tagged_discriminators = branches
            .iter()
            .map(tagged_object_discriminator)
            .collect::<Option<Vec<_>>>();
        if let Some(discriminators) = tagged_discriminators {
            if outer_type.is_some() {
                return Err(GenerationError::invalid(format!(
                    "{context} combines a tagged object union with an outer type"
                )));
            }
            let Some((discriminator_name, _)) = discriminators.first() else {
                unreachable!("empty oneOf rejected above");
            };
            let mut seen = BTreeSet::new();
            for (name, literal) in &discriminators {
                if name != discriminator_name || !seen.insert(literal.clone()) {
                    return Err(GenerationError::invalid(format!(
                        "{context} contains overlapping tagged oneOf branches"
                    )));
                }
            }
            return branches
                .iter()
                .map(|branch| render_schema(branch, context))
                .collect::<Result<Vec<_>, _>>()
                .map(|branches| branches.join(" | "));
        }

        let mut rendered = Vec::with_capacity(branches.len());
        let mut seen_literals = BTreeSet::new();
        for branch in branches {
            let branch_object = object(branch, context)?;
            if !branch_object.contains_key("enum") && !branch_object.contains_key("const") {
                return Err(GenerationError::invalid(format!(
                    "{context} contains unsupported ambiguous oneOf semantics"
                )));
            }
            let literals = if let Some(constant) = branch_object.get("const") {
                std::slice::from_ref(constant)
            } else {
                branch_object
                    .get("enum")
                    .and_then(Value::as_array)
                    .ok_or_else(|| {
                        GenerationError::invalid(format!(
                            "{context} contains a non-array oneOf enum"
                        ))
                    })?
                    .as_slice()
            };
            for literal in literals {
                render_literal(literal, context)?;
                let normalized = serde_json::to_string(literal).map_err(|error| {
                    GenerationError::invalid(format!(
                        "failed to normalize {context} oneOf literal: {error}"
                    ))
                })?;
                if !seen_literals.insert(normalized) {
                    return Err(GenerationError::invalid(format!(
                        "{context} contains overlapping oneOf literal branches"
                    )));
                }
            }
            if let Some(kind) = outer_type
                && !literal_schema_matches_type(branch_object, kind)
            {
                return Err(GenerationError::invalid(format!(
                    "{context} oneOf branch does not match outer type `{kind}`"
                )));
            }
            rendered.push(render_schema(branch, context)?);
        }
        return Ok(rendered.join(" | "));
    }

    match schema.get("type") {
        Some(Value::String(kind)) => render_typed_schema(kind, schema, context),
        Some(Value::Array(kinds)) => {
            if kinds.len() != 2 || !kinds.iter().any(|kind| kind.as_str() == Some("null")) {
                return Err(GenerationError::invalid(format!(
                    "{context} contains an unsupported type union"
                )));
            }
            let kind = kinds
                .iter()
                .find_map(|kind| {
                    let kind = kind.as_str()?;
                    (kind != "null").then_some(kind)
                })
                .ok_or_else(|| {
                    GenerationError::invalid(format!("{context} has no non-null type"))
                })?;
            Ok(format!(
                "{} | null",
                render_typed_schema(kind, schema, context)?
            ))
        }
        _ => Err(GenerationError::invalid(format!(
            "{context} has no supported type"
        ))),
    }
}

fn render_nullable_union(value: &Value, context: &str) -> Result<String, GenerationError> {
    let branches = value
        .as_array()
        .ok_or_else(|| GenerationError::invalid(format!("{context} contains a non-array anyOf")))?;
    if branches.len() != 2
        || branches
            .iter()
            .filter(|branch| branch.get("type").and_then(Value::as_str) == Some("null"))
            .count()
            != 1
    {
        return Err(GenerationError::invalid(format!(
            "{context} contains unsupported ambiguous anyOf semantics"
        )));
    }
    let null_branch = branches
        .iter()
        .find(|branch| branch.get("type").and_then(Value::as_str) == Some("null"))
        .expect("validated one null branch");
    if render_schema(null_branch, context)? != "null" {
        return Err(GenerationError::invalid(format!(
            "{context} contains an invalid nullable null branch"
        )));
    }
    let branch = branches
        .iter()
        .find(|branch| branch.get("type").and_then(Value::as_str) != Some("null"))
        .expect("validated one non-null branch");
    Ok(format!("{} | null", render_schema(branch, context)?))
}

fn render_typed_schema(
    kind: &str,
    schema: &Map<String, Value>,
    context: &str,
) -> Result<String, GenerationError> {
    match kind {
        "string" => {
            ensure_schema_keywords(schema, &["type"], context)?;
            Ok("string".to_owned())
        }
        "boolean" => {
            ensure_schema_keywords(schema, &["type"], context)?;
            Ok("boolean".to_owned())
        }
        "null" => {
            ensure_schema_keywords(schema, &["type"], context)?;
            Ok("null".to_owned())
        }
        "integer" => {
            ensure_schema_keywords(schema, &["format", "maximum", "minimum", "type"], context)?;
            let format = match schema.get("format") {
                Some(Value::String(format))
                    if matches!(
                        format.as_str(),
                        "uint" | "uint8" | "uint16" | "uint32" | "uint64" | "int32"
                    ) =>
                {
                    Some(format.as_str())
                }
                Some(Value::String(format)) => {
                    return Err(GenerationError::invalid(format!(
                        "{context} uses unsupported integer format `{format}`"
                    )));
                }
                Some(_) => {
                    return Err(GenerationError::invalid(format!(
                        "{context} integer format must be a string"
                    )));
                }
                None => None,
            };
            let minimum = schema.get("minimum").and_then(Value::as_f64);
            let maximum = schema.get("maximum").and_then(Value::as_f64);
            let (expected_minimum, expected_maximum) = match format {
                Some("uint") | Some("uint64") => (0.0, MAX_SAFE_INTEGER),
                Some("uint8") => (0.0, u8::MAX as f64),
                Some("uint16") => (0.0, u16::MAX as f64),
                Some("uint32") => (0.0, u32::MAX as f64),
                Some("int32") => (i32::MIN as f64, i32::MAX as f64),
                None => (MIN_SAFE_INTEGER, MAX_SAFE_INTEGER),
                Some(_) => unreachable!("integer format validated above"),
            };
            if minimum != Some(expected_minimum) || maximum != Some(expected_maximum) {
                return Err(GenerationError::invalid(format!(
                    "{context} integer range does not match its JavaScript safe-number mapping"
                )));
            }
            Ok("number".to_owned())
        }
        "array" => {
            ensure_schema_keywords(schema, &["items", "maxItems", "minItems", "type"], context)?;
            let items = schema.get("items").ok_or_else(|| {
                GenerationError::invalid(format!("{context} array has no item schema"))
            })?;
            let item = render_schema(items, context)?;
            match (schema.get("minItems"), schema.get("maxItems")) {
                (None, None) => Ok(format!("Array<{item}>")),
                (Some(minimum), Some(maximum)) if minimum == maximum => {
                    let length = minimum.as_u64().ok_or_else(|| {
                        GenerationError::invalid(format!(
                            "{context} fixed array length must be a non-negative integer"
                        ))
                    })?;
                    if length > 64 {
                        return Err(GenerationError::invalid(format!(
                            "{context} fixed array length exceeds the generator limit"
                        )));
                    }
                    Ok(format!(
                        "[{}]",
                        std::iter::repeat_n(item, length as usize)
                            .collect::<Vec<_>>()
                            .join(", ")
                    ))
                }
                _ => Err(GenerationError::invalid(format!(
                    "{context} contains unsupported variable array bounds"
                ))),
            }
        }
        "object" => {
            ensure_schema_keywords(
                schema,
                &["additionalProperties", "properties", "required", "type"],
                context,
            )?;
            render_object(schema, context)
        }
        other => Err(GenerationError::invalid(format!(
            "{context} uses unsupported type `{other}`"
        ))),
    }
}

fn render_object(schema: &Map<String, Value>, context: &str) -> Result<String, GenerationError> {
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| GenerationError::invalid(format!("{context} object has no properties")))?;
    let required = match schema.get("required") {
        Some(Value::Array(required)) => required
            .iter()
            .map(|name| {
                name.as_str().map(str::to_owned).ok_or_else(|| {
                    GenerationError::invalid(format!(
                        "{context} contains a non-string required property"
                    ))
                })
            })
            .collect::<Result<BTreeSet<_>, _>>()?,
        None => BTreeSet::new(),
        Some(_) => {
            return Err(GenerationError::invalid(format!(
                "{context} contains a non-array required declaration"
            )));
        }
    };
    if let Some(missing) = required.iter().find(|name| !properties.contains_key(*name)) {
        return Err(GenerationError::invalid(format!(
            "{context} requires missing property `{missing}`"
        )));
    }
    if schema
        .get("additionalProperties")
        .is_some_and(|value| value != &Value::Bool(false))
    {
        return Err(GenerationError::invalid(format!(
            "{context} contains unsupported additionalProperties"
        )));
    }

    let mut fields = Vec::with_capacity(properties.len());
    for (name, property) in properties {
        let optional = if required.contains(name) { "" } else { "?" };
        let name = if is_typescript_identifier(name) {
            name.clone()
        } else {
            serde_json::to_string(name).expect("serializing a property name cannot fail")
        };
        fields.push(format!(
            "{name}{optional}: {}",
            render_schema(property, context)?
        ));
    }
    Ok(format!("{{ {}; }}", fields.join("; ")))
}

fn render_literal(value: &Value, context: &str) -> Result<String, GenerationError> {
    match value {
        Value::String(_) | Value::Bool(_) | Value::Null => {
            serde_json::to_string(value).map_err(|error| {
                GenerationError::invalid(format!("failed to render {context} literal: {error}"))
            })
        }
        _ => Err(GenerationError::invalid(format!(
            "{context} contains an unsupported non-string enum/const literal"
        ))),
    }
}

fn is_typescript_identifier(value: &str) -> bool {
    let mut bytes = value.bytes();
    let Some(first) = bytes.next() else {
        return false;
    };
    (first.is_ascii_alphabetic() || matches!(first, b'_' | b'$'))
        && bytes.all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'$'))
}

fn object<'a>(value: &'a Value, context: &str) -> Result<&'a Map<String, Value>, GenerationError> {
    value
        .as_object()
        .ok_or_else(|| GenerationError::invalid(format!("{context} must be an object")))
}

fn object_field<'a>(
    value: &'a Map<String, Value>,
    field: &str,
    context: &str,
) -> Result<&'a Map<String, Value>, GenerationError> {
    value
        .get(field)
        .ok_or_else(|| GenerationError::invalid(format!("{context} is missing `{field}`")))
        .and_then(|value| object(value, &format!("{context}.{field}")))
}

fn required_string<'a>(
    value: &'a Map<String, Value>,
    field: &str,
    context: &str,
) -> Result<&'a str, GenerationError> {
    value
        .get(field)
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| GenerationError::invalid(format!("{context} requires string `{field}`")))
}

#[cfg(test)]
mod tests {
    use super::*;

    const OPENAPI: &str = include_str!("../../../openapi/server-api.json");
    const TYPESCRIPT: &str =
        include_str!("../../../web/workspace/src/lib/generated/repository-api.ts");

    #[test]
    fn checked_in_repository_typescript_is_current() {
        assert_eq!(
            generate_repository_typescript(OPENAPI).unwrap(),
            TYPESCRIPT,
            "regenerate with `cargo run -q -p server-api --example generate_repository_openapi_types`",
        );
    }

    #[test]
    fn output_records_authority_and_preserves_openapi_nullability() {
        let output = generate_repository_typescript(OPENAPI).unwrap();
        assert!(output.contains(&format!(
            "@generated by {GENERATOR_NAME}@{GENERATOR_VERSION}"
        )));
        assert!(output.contains("Input contract: 0.1.0 (sha256:"));
        assert!(output.contains("export type RepositorySourceKind = \"local_path\" | \"file\" | \"ssh\" | \"https\" | \"invalid\""));
        assert!(output.contains("git?: GitRepositorySummary | null"));
        assert!(output.contains("default_ref?: string | null"));
        assert!(!output.contains("export type string ="));
    }

    #[test]
    fn generator_rejects_lossy_safe_integer_and_union_changes() {
        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositorySummary"]["properties"]["source_revision"]["maximum"] =
            serde_json::json!(9_007_199_254_740_992_u64);
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(error.to_string().contains("safe-number"));

        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositorySummary"]["properties"]["source_revision"]["minimum"] =
            serde_json::json!(-1);
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(error.to_string().contains("safe-number"));

        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositorySummary"]["properties"]["source_revision"]["maximum"] =
            serde_json::json!(9_007_199_254_740_990_u64);
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(error.to_string().contains("safe-number"));

        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositorySummary"]["properties"]["source_revision"]["format"] =
            serde_json::json!("int64");
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(error.to_string().contains("unsupported integer format"));

        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositorySummary"]["properties"]["git"]["anyOf"]
            .as_array_mut()
            .unwrap()
            .push(serde_json::json!({"type": "string"}));
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(error.to_string().contains("ambiguous anyOf"));
    }

    #[test]
    fn generator_rejects_lossy_reference_siblings() {
        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositorySummary"]["properties"]["source"]["maxLength"] =
            serde_json::json!(1);
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(error.to_string().contains("unsupported `$ref` sibling"));
    }

    #[test]
    fn generator_rejects_lossy_operation_reference_siblings() {
        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["paths"]["/api/repositories"]["get"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["maxItems"] = serde_json::json!(1);
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(error.to_string().contains("unsupported `$ref` sibling"));
    }

    #[test]
    fn generator_rejects_unimplemented_ordinary_schema_keywords() {
        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositorySource"]["properties"]["uri"]["maxLength"] =
            serde_json::json!(1);
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(
            error
                .to_string()
                .contains("unsupported schema keyword `maxLength`")
        );

        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositoryListResponse"]["properties"]["items"]["uniqueItems"] =
            serde_json::json!(true);
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(
            error
                .to_string()
                .contains("unsupported schema keyword `uniqueItems`")
        );
    }

    #[test]
    fn generator_rejects_discarded_combined_schema_constraints() {
        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["DiagnosticSeverity"]["const"] =
            serde_json::json!("info");
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(
            error
                .to_string()
                .contains("unsupported schema keyword `enum`")
        );

        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        let null_branch =
            document["components"]["schemas"]["RepositorySummary"]["properties"]["git"]["anyOf"]
                .as_array_mut()
                .unwrap()
                .iter_mut()
                .find(|branch| branch.get("type").and_then(Value::as_str) == Some("null"))
                .unwrap();
        null_branch["maxLength"] = serde_json::json!(1);
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(
            error
                .to_string()
                .contains("unsupported schema keyword `maxLength`")
        );

        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositorySourceKind"]["type"] =
            serde_json::json!("string");
        document["components"]["schemas"]["RepositorySourceKind"]["oneOf"][0] =
            serde_json::json!({"const": true, "type": "boolean"});
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(
            error
                .to_string()
                .contains("oneOf branch does not match outer type")
        );

        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["RepositorySourceKind"]["oneOf"]
            .as_array_mut()
            .unwrap()
            .push(serde_json::json!({"const": "invalid", "type": "string"}));
        let error = generate_repository_typescript(&document.to_string()).unwrap_err();
        assert!(error.to_string().contains("overlapping oneOf literal"));
    }

    #[test]
    fn generator_is_bounded_to_the_repository_operation_contract() {
        let mut document: Value = serde_json::from_str(OPENAPI).unwrap();
        document["components"]["schemas"]["UnmigratedDomain"] = serde_json::json!({
            "type": "object",
            "properties": {"pretend": {"type": "string"}},
            "required": ["pretend"],
            "additionalProperties": false
        });
        let output = generate_repository_typescript(&document.to_string()).unwrap();
        assert!(!output.contains("UnmigratedDomain"));
    }
}
